# .mise.toml is linked from user directory via confs/.config/mise/config.toml
# to make it recognized from renovate

[tools]
node = "24.12.0"
"npm:@anthropic-ai/claude-code" = "2.0.74"
"npm:ccusage" = "15.9.7"
"npm:wrangler" = "4.30.0"
"npm:@openai/codex" = "0.76.0"
uv = "0.8.8"
gh = "2.78.0"
rust = "1.92.0"
flutter = "3.38.5-stable"
"npm:firebase-tools" = "14.27.0"
bun = "1.3.5"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
