# .mise.toml is linked from user directory via confs/.config/mise/config.toml
# to make it recognized from renovate

[tools]
node = "24.13.1"
"npm:@anthropic-ai/claude-code" = "2.1.49"
"npm:wrangler" = "4.67.0"
"npm:@openai/codex" = "0.104.0"
uv = "0.10.4"
gh = "2.78.0"
rust = "1.93.1"
flutter = "3.41.2-stable"
"npm:firebase-tools" = "15.7.0"
bun = "1.3.9"
ollama = "0.13.4"
ripgrep = "15.1.0"
go = "1.26.0"
jq = "1.8.1"
yq = "4.52.4"
awscli = "2.33.31"
terraform = "1.14.5"
"go:github.com/d-kuro/gwq/cmd/gwq" = "0.0.13"
"go:github.com/x-motemen/ghq" = "1.9.4"
pnpm = "10.30.1"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
